version: '3'
networks:
  my_proxy_network:
    driver: bridge
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
      # - ./php.ini:/etc/php/8.1/apache2/php.ini 
    ports:
      - "8082:80"
  
  mysql:
    image: mysql:latest
    environment:
      MYSQL_HOST: host
      MYSQL_ROOT_PASSWORD: Aa!22071990
      MYSQL_DATABASE: dating
      MYSQL_USER: vitik
      MYSQL_PASSWORD: Aa!11111
    volumes:
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
    ports:
      - "3306:3306"
